apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-attachment
spec:
  selector:
    matchLabels:
      app: attachment
  replicas: 1
  template:
    metadata:
      labels:
        app: attachment
    spec:
      containers:
      - name: attachmentapp
        image: 211125685751.dkr.ecr.ap-northeast-2.amazonaws.com/woorizip-attachment:20240508012606
        ports:
        - containerPort: 9999

---

apiVersion: v1
kind: Service
metadata:
  name: service-attachment
spec:
  selector:
    app: attachment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9999
  type: NodePort

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-helloworld
  annotations:
    alb.ingress.kubernetes.io/group.name: teamwaf
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:211125685751:certificate/c7979fef-a310-4ce3-9ead-80528f822f61
    external-dns.alpha.kubernetes.io/hostname: file.teamwaf.com

spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-attachment
              port:
                number: 80