apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-attachment
spec:
  selector:
    matchLabels:
      app: attachment
  replicas: 1
  template:
    metadata:
      labels:
        app: attachment
    spec:
      containers:
      - name: attachmentapp
        image: 211125685751.dkr.ecr.ap-northeast-2.amazonaws.com/woorizip-attachment:20240507123845
        ports:
        - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: service-attachment
spec:
  selector:
    app: attachment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9999
  type: NodePort